function show_eig(eig_data, is_visible, ts)
    n = length(eig_data);
    num_in = 0;
    num_out = 0;
    for i=1:n
        if IsInUnitCircle(eig_data(i))
            num_in = num_in + 1;
            scatter(real(eig_data(i)),imag(eig_data(i)), ...
            'Marker', '^', ...
            'MarkerFaceColor', 'b', ...
            'MarkerEdgeColor', 'b', ...
            'SizeData', 50, ...
            "Visible", is_visible);
        else
            num_out = num_out + 1;
            scatter(real(eig_data(i)),imag(eig_data(i)), ...
            'Marker', 'x', ...
            'MarkerFaceColor', 'r', ...
            'MarkerEdgeColor', 'r', ...
            'LineWidth', 1.5, ...
            'SizeData', 200, ...
            "Visible", is_visible);
            text(real(eig_data(i))+0.1,imag(eig_data(i)), ...
                "("+num2str(real(eig_data(i)),8)+","+ ...
                num2str(imag(eig_data(i)),8)+")","Color","Red", ...
                "Interpreter","latex","FontSize",12);
        end
        hold on
    end
    t=0:0.01:2*pi;
    plot(cos(t),sin(t),"k","LineWidth",2.5, "Visible", is_visible)
    hold off
    grid on
    axis equal
    xlabel("Re","FontSize",15,"Interpreter","latex");
    ylabel("Im","FontSize",15,"Interpreter","latex");
    title(["Sampling Time "+num2str(1000*ts)+" ms", ...
        num2str(num_in)+" stable, "+num2str(num_out)+" unstable"], ...
        "FontSize",15,"Interpreter","latex");
end

